<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For each key, resolves the
  English text: this mod's own Mod/Languages/English file+key if one exists, otherwise the native
  English value read from the upstream Flavor Text / Flavor Text Extended def (this mod carries no
  Defs of its own — it is a pure DefInjected/Keyed translation over those two mods' Defs, found in
  the sibling checkouts FlavorText/FlavorText and FlavorText/FlavorTextExtended).

  Original column: this mod has no non-English source language (Flavor Text and Flavor Text
  Extended are themselves English-authored), so Original always equals English; said once here
  rather than on every row, per Generate-FrenchReview.ps1's precedent in FoodCourt.

  Only Flavor Text Extended has a local dev checkout (sibling FlavorText/FlavorTextExtended);
  base Flavor Text (hekmo) has none in this tree (STATUS.md, upstream_mod_remotes: N/A) — its
  Defs are not readable here, so any key owned solely by it resolves to "not found" and needs
  checking by hand against the installed Workshop copy.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md'),
    [string[]]$UpstreamDefsRoots = @(
        (Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) 'FlavorTextExtended/Mod/Defs')
    )
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField([string]$key) {
    # key looks like "DefName.field" or "DefName.stages.N.field" or "DefName.tools.N.label"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $cur.$p
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$script:defFiles = @()
foreach ($defsRoot in $UpstreamDefsRoots) {
    if (Test-Path $defsRoot) {
        $script:defFiles += (Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName })
    }
}
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``scripts/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod translates Flavor Text and Flavor")
[void]$out.AppendLine("Text Extended, both authored in English with no separate non-English source; English is the")
[void]$out.AppendLine("original for every row.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after the gender-agreement rule of 2026-09-30.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $key
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        elseif ($null -ne $orig) { $en = $orig }
        if ($null -eq $orig) { $orig = $en }
        if ($null -eq $orig) { $orig = '*(not found - check by hand)*' }
        if ($null -eq $en) { $en = '*(not found - check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
